### ISSUE TITLE
add updatebot into the fabric8io/builder-clients

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/updatebot#1]
https://github.com/fabric8io-images/builder-clients

and setup CI / CD so that each updatebot release updates the builder clients

once updatebot is released we should be able to just copy the io.fabric8.updatebot:updatebot.jar to a file called updatebot on the `$PATH`

**Comment by rawlingsj** [comment]
builder-clients doesn't have java so I've added it to **maven-builder** instead https://github.com/fabric8io-images/maven-builder/blob/master/Dockerfile#L39-L41 - the next release of updatebot should update the version and trigger a new maven builder pod release.
